HMIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('',include('patients.urls')),
    path('__reload__/', include('django_browser_reload.urls')),

]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', views.login, name='login'),
     path('logout', views.custom_logout_view, name='logout'),
    path('adduser/', views.adduser, name='adduser'),
     path('viewusers/', views.viewusers, name='viewusers'),
]

core/urls.py
# core/urls.py
from django.urls import path
from . import views  # Ensure this import is correct

app_name = 'core'

urlpatterns = [
    path('defualt/', views.index, name='index'),
    path('about/', views.about, name='about'),


]

patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('biodata/', views.biodata, name='biodata'),
    path('addbiodata/', views.addbiodata, name='addbiodata'),
    path('servicecategory/', views.servicecategory, name='servicecategory'),
    path('addservice/', views.addservice, name='addservice'),
    path('getservices/', views.getservices, name='getservices'),
    path('addservicecategory/', views.addservicecategory, name='addservicecategory'),
    path('adddrugcategory/', views.adddrugcategory, name='adddrugcategory'),
    path('getdrugcategory/', views.getdrugcategory, name='getdrugcategory'),
    path('adddrug/', views.adddrug, name='adddrug'),
    path('getdrug/', views.getdrug, name='getdrug'),
    path('tribes/', views.tribes, name='tribes'),
    path('addtribe/', views.addtribe, name='addtribe'),
    path('api/day-counts/', views.day_counts_view, name='day-counts'),
    path('api/tribenames/', views.gettribedropdown, name='tribenames'),
    path('createprovidedservice/', views.createprovidedservice, name='createprovidedservice'),
    path('load_form/', views.load_provided_service_form, name='load_provided_service_form'),
    path('load-services/', views.load_services, name='load_services'),
    path('getprovidedserviceview/', views.getprovidedserviceview, name='getprovidedserviceview'),
    path('servicerecipt/', views.servicerecipt, name='servicerecipt'),
    path('getprovidedserviceviewbyPatientId/', views.getprovidedserviceviewbyPatientId, name='getprovidedserviceviewbyPatientId'),

    
    
    
   

  
    

]

core/models.py
from django.db import models

# Create your models here.

core/views.py
# core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from io import BytesIO
from patients.models import Biodata
from django.contrib.auth.decorators import login_required

@login_required
def about(request):
    return render(request, 'core/about.html')

@login_required
def index(request):
    return render(request, 'core/index.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<header class="py-12 text-center bg-slate-200">
    <h1 class="text-3xl">THIS IS THE ABOUT US</h1>

</header>
{% endblock %}

core/templates/core/base.html
{% load static tailwind_tags %}
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'menu.js' %}" defer></script>
    <script src="{% static 'patientgraph.js' %}" defer></script>
    <title>salama1</title>
</head>

<body class="overflow-hidden">
    <div class="flex w-screen h-screen">

        <!-- Sidebar -->
        <div id="menu" class="flex-col bg-gray-900 w-64 hidden lg:flex">

            <div class="flex flex-col items-center">
                <div class="mb-2 mt-3">
                    <img src="{% static 'homelogo.png' %}" class="h-36">
                </div>
                <h1 class="text-white text-3xl mt-0">
                    <a href="">SALAMA1</a>
                </h1>
            </div>

            <nav class="flex flex-col p-4 space-y-4  text-white">
                <a class="flex items-center p-2 hover:bg-gray-700  bg-gray-800 rounded" href="{% url 'core:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6 mr-2">
                        <path
                            d="M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z" />
                        <path
                            d="m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z" />
                    </svg>

                    Dashboad
                </a>


                <div class="relative group">
                    <button class="flex items-center p-2 w-full text-left hover:bg-gray-700 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z" />
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        </svg>
                        Settings
                    </button>
                    <div
                        class="relative left-0 mt-2 w-48 bg-gray-800 text-white rounded-lg shadow-lg hidden group-hover:block">
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:tribes' %}">Tribes</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:servicecategory' %}">Service
                            Category</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:getservices' %}">Service</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:getdrugcategory' %}">Drug
                            Category</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:getdrug' %}">Drugs</a>

                    </div>
                </div>
                <div class="relative group">
                    <button class="flex items-center p-2 w-full text-left hover:bg-gray-700 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M15 9h3.75M15 12h3.75M15 15h3.75M4.5 19.5h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Zm6-10.125a1.875 1.875 0 1 1-3.75 0 1.875 1.875 0 0 1 3.75 0Zm1.294 6.336a6.721 6.721 0 0 1-3.17.789 6.721 6.721 0 0 1-3.168-.789 3.376 3.376 0 0 1 6.338 0Z" />
                        </svg>
                        Manage Users
                    </button>
                    <div
                        class="relative left-0 mt-2 w-48 bg-gray-800 text-white rounded-lg shadow-lg hidden group-hover:block">
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'account:viewusers' %}">Manage
                            Users</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="/">View Logs</a>
                    </div>
                </div>
                <div class="relative group">
                    <button class="flex items-center p-2 w-full text-left hover:bg-gray-700 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="m7.875 14.25 1.214 1.942a2.25 2.25 0 0 0 1.908 1.058h2.006c.776 0 1.497-.4 1.908-1.058l1.214-1.942M2.41 9h4.636a2.25 2.25 0 0 1 1.872 1.002l.164.246a2.25 2.25 0 0 0 1.872 1.002h2.092a2.25 2.25 0 0 0 1.872-1.002l.164-.246A2.25 2.25 0 0 1 16.954 9h4.636M2.41 9a2.25 2.25 0 0 0-.16.832V12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 12V9.832c0-.287-.055-.57-.16-.832M2.41 9a2.25 2.25 0 0 1 .382-.632l3.285-3.832a2.25 2.25 0 0 1 1.708-.786h8.43c.657 0 1.281.287 1.709.786l3.284 3.832c.163.19.291.404.382.632M4.5 20.25h15A2.25 2.25 0 0 0 21.75 18v-2.625c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125V18a2.25 2.25 0 0 0 2.25 2.25Z" />
                        </svg>
                        Add Records
                    </button>
                    <div
                        class="relative left-0 mt-2 w-48 bg-gray-800 text-white rounded-lg shadow-lg hidden group-hover:block">
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'patients:biodata' %}">Patient
                            Details</a>
                        <a class="block px-4 py-2 hover:bg-gray-700"
                            href="{% url 'patients:getprovidedserviceview' %}">Issued Services</a>
                        <a </div>
                    </div>

                    <a class="flex items-center p-2 hover:bg-gray-700 rounded" href="/">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="size-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
                        </svg>


                        Help
                    </a>
            </nav>


        </div>

        <!-- Main Content -->
        <div class="flex-1 flex flex-col">
            <div class="pt-3 pl-3 pr-3 bg-gray-100 h-16 flex">
                <!-- the Humbuger location -->
                <button id="menu-toggle" class="text-white lg:hidden mr-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="#FF5733" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 6h15M4.5 12h15M4.5 18h15" />
                    </svg>

                </button>

                <!-- Content for the first section -->
                <h1 class="text-2xl font-bold hidden lg:flex ">SALAMA1 POLYCLINIC MANAGEMENT SYSTEM</h1>
                <h1 class="text-2xl font-bold lg:hidden ">SPMS</h1>

                <div class="ml-auto flex">
                    {% if user.is_authenticated %}
                    <div class="inline-block text-left">
                        <div class="">
                            <button type="button"
                                class="inline-flex  w-full rounded-md  border-gray-300 shadow-sm items-center font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                                id="menu-button" aria-expanded="true" aria-haspopup="true">


                                <ul class="list-none flex p-2">
                                    <li class="mr-2 font-bold">{{ user.name }}</li>
                                    <li class="mr-2 "> ({{ user.role }})</li>
                                    <!-- or use user.username if using a standard user model -->

                                </ul>
                            </button>
                        </div>

                        <div class="origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                            role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1"
                            style="display: none;" id="menu-dropdown">
                            <div class="py-1" role="none">
                                <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Change Password</a>
                                <form method="POST" action="{% url 'account:logout' %}" role="none">
                                    {% csrf_token %}
                                    <button type="submit" class="text-gray-700 block w-full text-left px-4 py-2 text-sm"
                                        role="menuitem" tabindex="-1" id="menu-item-3">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>

                    {% else %}

                    {% endif %}
                </div>




            </div>
            <div class="p-0.5 bg-blue-600">

            </div>
            <div class=" bg-slate-00 overflow-auto">

                {% block content %}

                {% endblock %}


            </div>
            <script src="{% static 'datatablemin.js' %}" defer></script>

        </div>
    </div>
    </div>
</body>

</html>

<script>
    document.getElementById('menu-button').addEventListener('click', function (event) {
        event.preventDefault();
        const dropdown = document.getElementById('menu-dropdown');
        dropdown.style.display = dropdown.style.display === 'none' ? 'block' : 'none';
    });

    // Hide dropdown when clicking outside
    window.addEventListener('click', function (event) {
        const dropdown = document.getElementById('menu-dropdown');
        const button = document.getElementById('menu-button');
        if (!button.contains(event.target)) {
            dropdown.style.display = 'none';
        }
    });
</script>

core/templates/core/test.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <script src="{% static 'menu.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>Salama1</title>
</head>
<body>
    <div class="flex w-screen h-screen">
        <!-- Sidebar -->
        <div id="menu" class="flex-col bg-gray-900 w-64 hidden lg:flex">
            <div class="flex flex-col items-center">
                <div class="mb-2 mt-3">
                    <img src="{% static 'homelogo.png' %}" class="h-36" alt="Home Logo">
                </div>
                <h1 class="text-white text-3xl mt-0">
                    <a href="#">SALAMA1</a>
                </h1>
            </div>
            <nav class="flex flex-col p-4 space-y-4 text-white">
                <a class="flex items-center p-2 hover:bg-gray-700 bg-gray-800 rounded" href="{% url 'core:index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 mr-2">
                        <path d="M11.47 3.841a.75.75 0 0 1 1.06 0l8.69 8.69a.75.75 0 1 0 1.06-1.061l-8.689-8.69a2.25 2.25 0 0 0-3.182 0l-8.69 8.69a.75.75 0 1 0 1.061 1.06l8.69-8.689Z" />
                        <path d="m12 5.432 8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 0 1-.75-.75v-4.5a.75.75 0 0 0-.75-.75h-3a.75.75 0 0 0-.75.75V21a.75.75 0 0 1-.75.75H5.625a1.875 1.875 0 0 1-1.875-1.875v-6.198a2.29 2.29 0 0 0 .091-.086L12 5.432Z" />
                    </svg>
                    Dashboard
                </a>

                <!-- Settings Dropdown -->
                <div class="relative group">
                    <button class="flex items-center p-2 w-full text-left hover:bg-gray-700 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                        </svg>
                        Settings
                    </button>
                    <div class="relative left-0 mt-2 w-48 bg-gray-800 text-white rounded-lg shadow-lg hidden group-hover:block">
                        <a class="block px-4 py-2 hover:bg-gray-700" href="/">Add Service Category</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="/">Add Service</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="/">Add Drug Price</a>
                    </div>
                </div>

                <!-- Manage Users Dropdown -->
                <div class="relative group">
                    <button class="flex items-center p-2 w-full text-left hover:bg-gray-700 rounded">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 9h3.75M15 12h3.75M15 15h3.75M4.5 19.5h15a2.25 2.25 0 0 0 2.25-2.25V6.75A2.25 2.25 0 0 0 19.5 4.5h-15a2.25 2.25 0 0 0-2.25 2.25v10.5A2.25 2.25 0 0 0 4.5 19.5Zm6-10.125a1.875 1.875 0 1 1-3.75 0 1.875 1.875 0 0 1 3.75 0Zm1.294 6.336a6.721 6.721 0 0 1-3.17.789 6.721 6.721 0 0 1-3.168-.789 3.376 3.376 0 0 1 6.338 0Z" />
                        </svg>
                        Manage Users
                    </button>
                    <div class="relative left-0 mt-2 w-48 bg-gray-800 text-white rounded-lg shadow-lg hidden group-hover:block">
                        <a class="block px-4 py-2 hover:bg-gray-700" href="{% url 'account:viewusers' %}">Manage Users</a>
                        <a class="block px-4 py-2 hover:bg-gray-700" href="#">Settings</a>
                    </div>
                </div>
            </nav>
        </div>

        <!-- Main Content -->
        <main class="flex-1 p-4">
            <canvas id="myChart" width="400" height="200"></canvas>
        </main>
    </div>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const ctx = document.getElementById('myChart').getContext('2d');
        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
              label: '# of Votes',
              data: [12, 19, 3, 5, 2, 3],
              borderWidth: 1,
              backgroundColor: 'rgba(75, 192, 192, 0.2)',
              borderColor: 'rgba(75, 192, 192, 1)',
            }]
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
      });
    </script>
</body>
</html>