HMIS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('',include('patients.urls')),
    path('__reload__/', include('django_browser_reload.urls')),

]

patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('biodata/', views.biodata, name='biodata'),
    path('addbiodata/', views.addbiodata, name='addbiodata'),
    path('servicecategory/', views.servicecategory, name='servicecategory'),
    path('addservice/', views.addservice, name='addservice'),
    path('getservices/', views.getservices, name='getservices'),
    path('addservicecategory/', views.addservicecategory, name='addservicecategory'),
    path('adddrugcategory/', views.adddrugcategory, name='adddrugcategory'),
    path('getdrugcategory/', views.getdrugcategory, name='getdrugcategory'),
    path('adddrug/', views.adddrug, name='adddrug'),
    path('getdrug/', views.getdrug, name='getdrug'),
    path('tribes/', views.tribes, name='tribes'),
    path('addtribe/', views.addtribe, name='addtribe'),
    path('api/day-counts/', views.day_counts_view, name='day-counts'),
    path('api/tribenames/', views.gettribedropdown, name='tribenames'),
    path('createprovidedservice/', views.createprovidedservice, name='createprovidedservice'),
    path('load_form/', views.load_provided_service_form, name='load_provided_service_form'),
    path('load-services/', views.load_services, name='load_services'),
    path('getprovidedserviceview/', views.getprovidedserviceview, name='getprovidedserviceview'),
    path('servicerecipt/', views.servicerecipt, name='servicerecipt'),
    path('getprovidedserviceviewbyPatientId/', views.getprovidedserviceviewbyPatientId, name='getprovidedserviceviewbyPatientId'),

    
    
    
   

  
    

]

patients/models.py
from datetime import datetime
import uuid
from django.db import models
from django.core.exceptions import ValidationError
from  account.models import User


# Create your models here.

class Tribes(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    tribe = models.CharField(max_length=150, default="")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.tribe
    
class Biodata(models.Model):
    Firstname = models.CharField(max_length=100, default="")
    Othernames = models.CharField(max_length=100, default="")
    Age = models.CharField(max_length=100, default="")
    weight = models.CharField(max_length=100, default="")
    sex = models.CharField(max_length=100, default="")
    height = models.CharField(max_length=100, default="")
    tribe = models.ForeignKey(Tribes, on_delete=models.SET_NULL, null=True) 
    Address = models.TextField(default="")
    Phone = models.CharField(max_length=100, default="")
    Emailaddress = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    day_of_week = models.CharField(max_length=10, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) 

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = datetime.now()
        # Set the day_of_week based on created_at
        if self.created_at:
            self.day_of_week = self.created_at.strftime('%A')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.Firstname
    
    
    

class ServiceCategory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    category = models.CharField(max_length=150, default="")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.category
    

class Service(models.Model):
    category = models.ForeignKey(ServiceCategory, on_delete=models.SET_NULL, null=True)
    service = models.CharField(max_length=100, default="")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.service
    

class Drugcategory(models.Model):
    category = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.category


class Drugs(models.Model):
    category = models.ForeignKey(Drugcategory, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=100, default="")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.category
    

    

class Providedservices(models.Model):
    patient = models.ForeignKey(Biodata, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(ServiceCategory, on_delete=models.SET_NULL, null=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.service)




    


            


    

patients/views.py
from itertools import count
from django.shortcuts import render
from .models import Biodata
from .models import ServiceCategory, Service, Drugcategory, Drugs
from .models import Tribes
from django.http import JsonResponse
from django.db.models import Count
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import BiodataForm
from .forms import ServiceCategoryForm, ServiceForm, drugcategoryForm, drugForm, tribeForm
from .models import Providedservices
from .forms import ProvidedServiceForm
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required




# Create your views here.
@login_required
def biodata(request):

    context = {
        'Biodatas': Biodata.objects.all()  # This will be available for both GET and POST requests
    }
        # Update context with the latest Biodata records
    day_counts = Biodata.objects.values('day_of_week').annotate(count=Count('id')).order_by('day_of_week')
    context['day_counts'] = list(day_counts)
    context['Biodatas'] = Biodata.objects.all()

    return render(request, 'patients/biodata.html', context)

@login_required
def day_counts_view(request):
    day_counts = Biodata.objects.values('day_of_week').annotate(count=Count('id')).order_by('day_of_week')
    return JsonResponse(list(day_counts), safe=False)

@login_required
def addbiodata(request):
    if request.method == 'POST':
        form = BiodataForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            return redirect('patients:biodata')  
    else:
        form = BiodataForm()
    
    return render(request, 'patients/addbiodata.html', {'form': form})

@login_required
def addservicecategory(request):
    if request.method == 'POST':
        form = ServiceCategoryForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            return redirect('patients:servicecategory') 
    else:
        form = ServiceCategoryForm()

    return render(request, 'patients/addservicecategory.html', {'form': form})



from django.shortcuts import render
from .models import ServiceCategory



@login_required
def servicecategory(request):
    context = {
        'categories': ServiceCategory.objects.all()  # Use a consistent and appropriate key name
    }
    return render(request, 'patients/servicecategory.html', context)

@login_required
def tribes(request):

    context = {
        'tribes' : Tribes.objects.all()
    }

    return render(request, 'patients/tribes.html', context)



@login_required    
def addtribe(request):
    if request.method == 'POST':
        form = tribeForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            messages.success(request, 'Tribe added successfully!')
            return redirect('patients:tribes')  # Adjust URL name as necessary
        else:
            messages.error(request, 'Please correct the errors below.')
            print(form.errors)  # For debugging
    else:
        form = tribeForm()

    return render(request, 'patients/addtribe.html', {'form': form})
@login_required
def addservice(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            return redirect('patients:getservices') 
    else:
        form = ServiceForm()

    return render(request, 'patients/addservice.html', {'form': form})

@login_required
def getservices(request):

    context = {
        'services' : Service.objects.all()
    }

    return render(request, 'patients/Services.html', context)

@login_required
def adddrugcategory(request):
    if request.method == 'POST':
        form = drugcategoryForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            return redirect('patients:getdrugcategory') 
    else:
        form = drugcategoryForm()

    return render(request, 'patients/adddrugcategory.html', {'form': form})

@login_required
def getdrugcategory(request):

    context = {
        'categories' : Drugcategory.objects.all()
    }

    return render(request, 'patients/drugcategory.html', context)
@login_required
def adddrug(request):
    if request.method == 'POST':
        form = drugForm(request.POST)
        if form.is_valid():
            formtosave = form.save(commit=False)
            formtosave.added_by = request.user
            formtosave.save()
            return redirect('patients:getdrug')
        else:
            print(form.errors)  # This line prints the form errors to the console
    else:
        form = drugForm()

    return render(request, 'patients/adddrug.html', {'form': form})


def getdrug(request):

    context = {
        'drugs' : Drugs.objects.all()
    }

    return render(request, 'patients/drug.html', context)

@login_required
def createprovidedservice(request):
    if request.method == 'POST':
        form = ProvidedServiceForm(request.POST)
        if form.is_valid():
            # Print individual values
            print("Form data:", request.POST)
            patient_id = request.POST.get('patient_id')
            category_id = request.POST.get('category')
            service_id = request.POST.get('service')



            provided_service = form.save(commit=False)
            try:
                patient = Biodata.objects.get(id=patient_id)
                provided_service.patient = patient
                provided_service.added_by = request.user
                provided_service.save()

                # Save patient_id in session
                request.session['patient_id'] = patient_id

                return redirect('patients:getprovidedserviceviewbyPatientId') 
            except Biodata.DoesNotExist:
                form.add_error(None, "Patient does not exist.")
    else:
        form = ProvidedServiceForm()

    return render(request, 'patients/providedservice.html', {'form': form})



@login_required
def load_provided_service_form(request):
    if request.method == 'GET':
        form = ProvidedServiceForm()
        html = render_to_string('patients/providedservice.html', {'form': form}, request=request)
        return JsonResponse({'html': html})
    



@login_required
def getprovidedserviceview(request):
    # Fetch all patients with their provided services and related services
    patients_with_services = Biodata.objects.prefetch_related('providedservices_set__service').all()
    
    context = {
        'patients_with_services': patients_with_services,
    }
    
    # For debugging, print the data to the console
    for patient in patients_with_services:
        print(f"Patient: {patient.Firstname} {patient.Othernames}")
        for provided_service in patient.providedservices_set.all():
            print(f"  Service: {provided_service.service.created_at}, Price: {provided_service.service}")
    
    return render(request, 'patients/patientsandservices.html', context)


# @login_required
# def getprovidedserviceviewbyPatientId(request):
#     # Get the patient ID from the session
#     patient_id = request.session.get('patient_id')
#     # Get the patient ID from the request query parameters
#     patient_id = request.GET.get('patient_id')  # Use request.POST.get() for POST requests
#     # Filter the Biodata objects based on the patient ID
#     patients_with_services = Biodata.objects.filter(id=patient_id).prefetch_related('providedservices_set__service')

#     context = {
#         'patients_with_services': patients_with_services,
#     }

#     # For debugging, print the data to the console
#     for patient in patients_with_services:
#         print(f"Patient: {patient.Firstname} {patient.Othernames}")
#         for provided_service in patient.providedservices_set.all():
#             print(f"  Service: {provided_service.service.created_at}, Price: {provided_service.service}")

#     return render(request, 'patients/servicerecipt.html', context)



def getprovidedserviceviewbyPatientId(request):
    # Get the patient ID from the session or query parameters
    patient_id = request.session.get('patient_id') or request.GET.get('patient_id')
    
    # Filter the Biodata objects based on the patient ID
    patients_with_services = Biodata.objects.filter(id=patient_id).prefetch_related('providedservices_set__service')

    # Print the retrieved data to the terminal
    for patient in patients_with_services:
        print(f"Patient: {patient.Firstname} {patient.Othernames}, Age: {patient.Age}, Weight: {patient.weight}")
        for provided_service in patient.providedservices_set.all():
            print(f"  Service: {provided_service.service.service}, Date: {provided_service.service.created_at}, Amount: {provided_service.service.price}")

    context = {
        'patients_with_services': patients_with_services,
    }

    return render(request, 'patients/servicerecipt.html', context)



#gettribesjasonfile
@login_required
def load_services(request):
    category_id = request.GET.get('category_id')
    services = Service.objects.filter(category_id=category_id).order_by('service')
    return JsonResponse({'services': list(services.values('id', 'service'))})
@login_required
def gettribedropdown(request):
    tribeName = Tribes.objects.values('id', 'tribe').order_by('tribe')
    return JsonResponse(list(tribeName), safe=False)


# @login_required
def servicerecipt(request):

patients/templates/patients/Services.html
{% extends 'core/base.html' %}

{% block content %}
<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({
            "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
            "iDisplayLength": 10
        });
    });
</script>

<div class="bg-gray-100 pl-3 pr-5 pt-3 pb-3">
    <div class="flex justify-between items-center mb-3">
        <p class="text-2xl font-semibold">Services</p>
        <a href="{% url 'patients:addservice' %}" class="rounded bg-green-600 text-white px-4 py-2 hover:bg-green-700">Add Service</a>
    </div>
    
    <div class="bg-white p-6 rounded-lg shadow-md border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
        <table id="bootstrapdatatable" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">S/No</th>
                    <th scope="col" class="px-6 py-3">Category</th>
                    <th scope="col" class="px-6 py-3">Drug</th>
                    <th scope="col" class="px-6 py-3">Price</th>
                    <th scope="col" class="px-6 py-3">Added on</th>
                    <th scope="col" class="px-6 py-3">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in services %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ forloop.counter }}
                    </th>
                    <td class="px-6 py-4">{{ i.category }}</td>
                    <td class="px-6 py-4">{{ i.service }}</td>
                    <td class="px-6 py-4">{{ i.price }}</td>
                    <td class="px-6 py-4">{{ i.created_at }}</td>
                    <td class="px-6 py-4">
                        <button type="button" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Update</button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="px-6 py-4 text-center">No service available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

patients/templates/patients/biodata.html
{% extends 'core/base.html' %}

{% block content %}

<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

<div class="bg-gray-100 pl-3 pr-5 pt-3 pb-3">
    <div class="flex justify-between items-center">
        <div class="mb-0">
            <p class="text-3xl font-semibold">Patients</p>
            <p class="text-xs text-blue-700">Select patient name to add service provide</p>

        </div>

        <a href="{% url 'patients:addbiodata' %}" class="rounded bg-green-600 text-white px-4 py-2 hover:bg-green-700">Add Patient</a>
    </div>

    <div class="bg-white p-6 rounded-lg shadow-md border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
        <table id="patientdatatables" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">S/No</th>
                    <th scope="col" class="px-6 py-3">Patient Name</th>
                    <th scope="col" class="px-6 py-3">Contact</th>
                    <th scope="col" class="px-6 py-3">Age</th>
                    <th scope="col" class="px-6 py-3">Weight</th>
                    <th scope="col" class="px-6 py-3">Height</th>
                    <th scope="col" class="px-6 py-3">Tribe</th>
                    <th scope="col" class="px-6 py-3">Sex</th>
                    <th scope="col" class="px-6 py-3">Address</th>
                    <th scope="col" class="px-6 py-3">Added by</th>
                    <th scope="col" class="px-6 py-3">Received On</th>
                    <th scope="col" class="px-6 py-3">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in Biodatas %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ forloop.counter }}
                    </th>
                    <td class="px-6 py-4">
                        <a href="#" class="patient-name text-blue-600 hover:underline font-bold" data-id="{{ i.id }}" data-name="{{ i.Firstname }} {{ i.Othernames }}">
                            {{ i.Firstname }} {{ i.Othernames }}
                        </a>
                        
                       
                            
                      
                    </td>
                    <td class="px-6 py-4">{{ i.Phone }}</td>
                    <td class="px-6 py-4">{{ i.Age }}</td>
                    <td class="px-6 py-4">{{ i.weight }}</td>
                    <td class="px-6 py-4">{{ i.height }}</td>
                    <td class="px-6 py-4">{{ i.tribe }}</td>
                    <td class="px-6 py-4">{{ i.sex }}</td>
                    <td class="px-6 py-4">{{ i.Address }}</td>
                    <td class="px-6 py-4">{{ i.added_by }}</td>
                    <td class="px-6 py-4">{{ i.created_at }}</td>
                    <td class="px-6 py-4">
                        <button type="button" data-id="{{ i.id }}"  class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Update</button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="11" class="px-6 py-4 text-center">No patient registered.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Modal HTML Structure -->
<div id="serviceModal" class="fixed z-10 inset-0 overflow-y-auto hidden">
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 transition-opacity" aria-hidden="true">
            <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
        </div>
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
        <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
            <div class="sm:flex sm:items-start">
                <div class="mt-3 text-center sm:mt-0 sm:text-left">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">
                        Provide Service for <span id="patientName" class="font-bold"></span>
                    </h3>
                    <div class="mt-2" id="formContainer">
                        <!-- The form will be dynamically inserted here via AJAX -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function () {
    if (!$.fn.DataTable.isDataTable('#patientdatatables')) {
        $('#patientdatatables').DataTable({
            "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
            "iDisplayLength": 10
        });
    }

    // Open modal when patient name is clicked
    $('.patient-name').click(function () {
        var patientName = $(this).data('name');
        var patientId = $(this).data('id');

        $('#patientName').text(patientName);

        // Fetch the form via AJAX
        $.get("{% url 'patients:load_provided_service_form' %}", function (data) {
            $('#formContainer').html(data.html);
            $('#patientId').val(patientId); // Set the patient ID after loading the form
            $('#serviceModal').removeClass('hidden');
        });
    });

    // Close modal
    $(document).on('click', '.close-modal', function () {
        $('#serviceModal').addClass('hidden');
    });
});

</script>



{% endblock %}

patients/templates/patients/drugcategory.html
{% extends 'core/base.html' %}

{% block content %}
<!-- DataTables CSS -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({
            "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
            "iDisplayLength": 10
        });
    });
</script>

<div class="bg-gray-100 pl-3 pr-5 pt-3 pb-3">
    <div class="flex justify-between items-center mb-3">
        <p class="text-xl font-semibold">Drug Category</p>
        <a href="{% url 'patients:adddrugcategory' %}" class="rounded bg-green-600 text-white px-4 py-2 hover:bg-green-700">Add Drug Catagory</a>
    </div>
    
    <div class="bg-white p-6 rounded-lg shadow-md border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
        <table id="bootstrapdatatable" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">S/No</th>
                    <th scope="col" class="px-6 py-3">Category</th>

                    <th scope="col" class="px-6 py-3">Added on</th>
                    <th scope="col" class="px-6 py-3">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for i in categories %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ forloop.counter }}
                    </th>
                    <td class="px-6 py-4">{{ i.category }}</td>
         
                    <td class="px-6 py-4">{{ i.created_at }}</td>
                    <td class="px-6 py-4">
                        <button type="button" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Update</button>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="px-6 py-4 text-center">No drugs available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

patients/templates/patients/providedservice.html
{% load widget_tweaks %}
<form id="serviceForm" method="post" action="{% url 'patients:createprovidedservice' %}">
    {% csrf_token %}
    <input id="patientId" name="patient_id" type="hidden">
   
    <div class="flex mb-2">
        <label for="password" class="w-40 text-sm font-medium text-gray-900 dark:text-white">Category</label>
        {% render_field form.category class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-72 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %}
    </div>
    <div class="flex mb-2">
        <label for="password" class="w-40 text-sm font-medium text-gray-900 dark:text-white">Service</label>
        {% render_field form.service class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-72 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %}
    </div>
    <div class="flex mb-2">
        <label for="password" class="w-40 text-sm font-medium text-gray-900 dark:text-white">Charge</label>
        {% render_field form.cost class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-72 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" %}
    </div>
    
        <div>
            
            <button type="button" class="close-modal bg-gray-300 text-gray-700 px-4 py-2 rounded hover:bg-gray-400">Cancel</button>
            <button type="submit" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700">Save</button>
        </div>
    
</form>

<script>
$('#id_category').change(function() {
    var category_id = $(this).val();
    $.ajax({
        url: '{% url "patients:load_services" %}',
        data: {
            'category_id': category_id
        },
        dataType: 'json',
        success: function(data) {
            var $service = $('#id_service');
            $service.empty();  
            if (data.services) {
                $.each(data.services, function(index, service) {
                    $service.append($('<option>', {
                        value: service.id,
                        text: service.service
                    }));
                });
            }
        },
        error: function(jqXHR, textStatus, errorThrown) {
            console.error('AJAX request failed:', textStatus, errorThrown);
        }
    });
});
</script>
    